import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("Usage: node scripts/render_job_feed.mjs <jobs.json> [outputFeedJs]");
  process.exit(2);
}

const outPath =
  process.argv[3] ||
  path.join(__dirname, "..", "public", "feed.js");

const raw = await readFile(inputPath, "utf8");
const parsed = JSON.parse(raw);
const jobs = Array.isArray(parsed) ? parsed : parsed?.jobs;
if (!Array.isArray(jobs)) {
  console.error("Input must be a JSON array or an object with a jobs array.");
  process.exit(2);
}

const payload = {
  generatedAt: new Date().toISOString(),
  jobs,
};

const js = `// Auto-generated by the daily job search automation.\nwindow.__JOB_FEED__ = ${JSON.stringify(
  payload,
  null,
  2,
)};\n`;

await writeFile(outPath, js);
console.log(`Wrote ${jobs.length} jobs to ${outPath}`);

